;;; -*- mode: common-lisp;   common-lisp-style: modern;    coding: utf-8; -*-
;;;

(in-package :cl-user)

(defpackage "_" (:use))


(DEFPACKAGE #:TEMPLETON
  (:NICKNAMES :TTON)
  (:SHADOWING-IMPORT-FROM #:WILBUR #:GET-VALUE)
  (:USE #:ELEPHANT #:HU.DWIM.STEFIL #:COMMON-LISP #:WILBUR #:HU.DWIM.DEF)
  (:IMPORT-FROM :WILBUR.TURTLE #:TURTLE-DB #:TURTLE-PARSER #:BNODES-OF #:INTERN-BNODE 
    #:PARSE-TURTLE-STRING #:PARSE-TURTLE-STREAM )
  (:EXPORT
    #:*GRAPHS*
    #:ALL-NAMED-GRAPHS
    #:ALL-PREFIXES
    #:COMMIT
    #:DB-ACCESS-STATS
    #:DB-INDEX-STATS
    #:DB-OF
    #:DICTIONARY-CLEAR
    #:DICTIONARY-SIZE
    #:DROP-GRAPH
    #:DROP-ALL-NAMED-GRAPHS
    #:EXTENDED-DB
    #:GET-PHASH
    #:GET-PHASH*
    #:GRAPH-CONTAINER
    #:IMPORT-GRAPH
    #:LOAD-SCHEMA
    #:MAKE-PHASH
    #:MAKE-PINDEX
    #:MAP-PHASH
    #:MERGE-RESOLVED-PREFIXES
    #:NAMED-GRAPH
    #:NAMED-GRAPH-DB
    #:NGDB
    #:NG
    #:ANG
    #:PHASH
    #:PHASH-HELP
    #:PHASH-MAP
    #:PHASH-SIZE
    #:PINDEX
    #:PINDEX-MAP
    #:PREFIX-DB
    #:PRINTV
    #:PUT-PHASH
    #:REGISTER-OBJECT
    #:REM-PHASH
    #:RESOLVE-PREFIX
    #:ROLLBACK
    #:SNAPSHOT-COMMIT
    #:SNAPSHOT-RESTORE
    #:SNAPSHOT-ROOT
    #:SNAPSHOT-SET
    #:STORABLE-GRAPH
    #:STORABLE-NODE
    #:STORABLE-NODE-DICTIONARY
    #:UNREGISTER-OBJECT
    #:TURTLE-DB
    #:TURTLE-PARSER
    #:BNODES-OF
    #:INTERN-BNODE 
    #:PARSE-TURTLE-STRING
    #:PARSE-TURTLE-STREAM
    #:WITH-GRAPH
    #:WITH-MERGED-GRAPHS
    ))
